provider:
  name: openfaas
  gateway: https://phxlvveba01.itplab.local
functions:
  nsxttagsync-vro:
    lang: powercli
    handler: ./handler
    image: cmstraka/veba-powershell-vro-tag-sync-to-nsxt:latest
    environment:
      write_debug: false
      read_debug: false
      function_debug: false
      skip_vro_cert_check: false
    secrets:
      - vro-secrets
    annotations:
      topic: com.vmware.cis.tagging.attach,com.vmware.cis.tagging.detach
      
      